
  CREATE TABLE "SCOTT"."P5ADMIN" 
   (	"AD_ID" VARCHAR2(20) NOT NULL ENABLE, 
	"AD_PW" VARCHAR2(20), 
	"AD_NAME" VARCHAR2(20), 
	"AD_EMPNO" VARCHAR2(20), 
	 CONSTRAINT "PK_P5ADMIN" PRIMARY KEY ("AD_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  
 
  CREATE TABLE "SCOTT"."P5CAROUSEL" 
   (	"carou_code" NUMBER NOT NULL ENABLE, 
	"carou_order" NUMBER, 
	"carou_img" VARCHAR2(100), 
	"carou_link" VARCHAR2(100), 
	"carou_date" DATE, 
	 CONSTRAINT "PK_P5CAROUSEL" PRIMARY KEY ("carou_code")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  
 
  CREATE TABLE "SCOTT"."P5FAQ" 
   (	"faq_code" NUMBER NOT NULL ENABLE, 
	"ad_id" VARCHAR2(20), 
	"faq_cate" VARCHAR2(300), 
	"faq_title" VARCHAR2(100), 
	"faq_detail" VARCHAR2(1000), 
	"faq_img" VARCHAR2(100), 
	 CONSTRAINT "PK_P5FAQ" PRIMARY KEY ("faq_code")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 FOREIGN KEY ("ad_id")
	  REFERENCES "SCOTT"."P5ADMIN" ("AD_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  
 
  CREATE TABLE "SCOTT"."P5MEETUP" 
   (	"MEETUP_CODE" NUMBER NOT NULL ENABLE, 
	"SZ_CODE" NUMBER NOT NULL ENABLE, 
	"MEETUP_BOOKDATE" DATE NOT NULL ENABLE, 
	"MEETUP_TITLE" VARCHAR2(100) NOT NULL ENABLE, 
	"MEETUP_SUBTITLE" VARCHAR2(100) NOT NULL ENABLE, 
	"MEETUP_DATE" DATE NOT NULL ENABLE, 
	"MEETUP_STIME" DATE NOT NULL ENABLE, 
	"MEETUP_FTIME" DATE NOT NULL ENABLE, 
	"MEETUP_CATE" VARCHAR2(20) NOT NULL ENABLE, 
	"MEETUP_IMG" VARCHAR2(100) NOT NULL ENABLE, 
	"MEETUP_DETAIL" VARCHAR2(1000) NOT NULL ENABLE, 
	"MEETUP_CAPA" NUMBER NOT NULL ENABLE, 
	"MEETUP_PARNO" NUMBER, 
	"MEETUP_PRICE" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "PK_P5MEETUP" PRIMARY KEY ("MEETUP_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  
 
  CREATE TABLE "SCOTT"."P5MEETUPPARTI" 
   (	"COL" NUMBER NOT NULL ENABLE, 
	"MEETUP_CODE" NUMBER NOT NULL ENABLE, 
	"MEETUP_PARTI_BOOKDATE" DATE, 
	"MEM_ID" VARCHAR2(20), 
	"MEETUP_PARTI_MCNT" NUMBER, 
	"MEETUP_PARTI_PRICE" NUMBER, 
	"MEETUP_PARTI_CURR" VARCHAR2(20), 
	"MEETUP_PARTI_COMM" VARCHAR2(1000), 
	"MEETUP_PARTI_REVIEW" DATE, 
	 CONSTRAINT "PK_P5MEETUPPARTI" PRIMARY KEY ("COL", "MEETUP_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  
 
  CREATE TABLE "SCOTT"."P5MEMBER" 
   (	"MEM_ID" VARCHAR2(200) NOT NULL ENABLE, 
	"MEM_PW" VARCHAR2(20) NOT NULL ENABLE, 
	"MEM_NAME" VARCHAR2(20) NOT NULL ENABLE, 
	"MEM_EMAIL" VARCHAR2(100) NOT NULL ENABLE, 
	"MEM_NICK" VARCHAR2(20) NOT NULL ENABLE, 
	"MEM_PHONE" VARCHAR2(20) NOT NULL ENABLE, 
	"MEM_ADDR" VARCHAR2(300) NOT NULL ENABLE, 
	"MEM_CATE" VARCHAR2(30) NOT NULL ENABLE, 
	"MEM_PROF" VARCHAR2(100) DEFAULT 'icon.png', 
	"active" DATE, 
	 CONSTRAINT "PK_P5MEMBER" PRIMARY KEY ("MEM_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  
 
  CREATE TABLE "SCOTT"."P5NOTICE" 
   (	"noti_code" NUMBER NOT NULL ENABLE, 
	"ad_id" VARCHAR2(20), 
	"noti_date" DATE, 
	"noti_title" VARCHAR2(100), 
	"noti_detail" VARCHAR2(1000), 
	"noti_img" VARCHAR2(100), 
	 CONSTRAINT "PK_P5NOTICE" PRIMARY KEY ("noti_code")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 FOREIGN KEY ("ad_id")
	  REFERENCES "SCOTT"."P5ADMIN" ("AD_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  
 
  CREATE TABLE "SCOTT"."P5QNA" 
   (	"QNA_CODE" NUMBER NOT NULL ENABLE, 
	"QNA_CATE" VARCHAR2(50), 
	"MEM_ID" VARCHAR2(20), 
	"QNA_DATE" DATE, 
	"QNA_TITLE" VARCHAR2(100), 
	"QNA_DETAIL" VARCHAR2(1000), 
	"QNA_OPEN" VARCHAR2(1), 
	"QNA_ANSW" VARCHAR2(1000), 
	"QNA_ADATE" DATE, 
	"AD_ID" VARCHAR2(20), 
	 CONSTRAINT "PK_P5QNA" PRIMARY KEY ("QNA_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  
 
  CREATE TABLE "SCOTT"."P5SEMIBOOK" 
   (	"SEMI_CODE" NUMBER NOT NULL ENABLE, 
	"MEM_ID" VARCHAR2(20) NOT NULL ENABLE, 
	"ZONE_CODE" NUMBER NOT NULL ENABLE, 
	"SEMI_BOOKDATE" DATE NOT NULL ENABLE, 
	"SEMI_TITLE" VARCHAR2(100) NOT NULL ENABLE, 
	"SEMI_SUBTITLE" VARCHAR2(100) NOT NULL ENABLE, 
	"SEMI_DATE" DATE NOT NULL ENABLE, 
	"SEMI_STIME" DATE NOT NULL ENABLE, 
	"SEMI_FTIME" DATE NOT NULL ENABLE, 
	"SEMI_CATE" VARCHAR2(20) NOT NULL ENABLE, 
	"SEMI_IMG" VARCHAR2(4000) NOT NULL ENABLE, 
	"SEMI_DETAIL" VARCHAR2(4000) NOT NULL ENABLE, 
	"SEMI_CAPA" NUMBER NOT NULL ENABLE, 
	"SEMI_PARNO" NUMBER NOT NULL ENABLE, 
	"SEMI_PRICE" NUMBER NOT NULL ENABLE, 
	"SEMI_CURR" VARCHAR2(20) NOT NULL ENABLE, 
	"ZONE_COMM" VARCHAR2(1000), 
	"ZONE_COMMDATE" DATE, 
	 CHECK (semi_cate IN ('IT기술','스포츠'	,'건강','음식','음악','가족','언어 문화', '영상제작', '기타')) ENABLE, 
	 CHECK (semi_curr IN ('입금대기','입금완료')) ENABLE, 
	 CONSTRAINT "PK_P5SEMIBOOK" PRIMARY KEY ("SEMI_CODE", "MEM_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  
 
  CREATE TABLE "SCOTT"."P5SEMIPARTI" 
   (	"PARTI_CODE" NUMBER NOT NULL ENABLE, 
	"SEMI_CODE" NUMBER NOT NULL ENABLE, 
	"PARTI_BOOKDATE" DATE NOT NULL ENABLE, 
	"MEM_ID" VARCHAR2(20) NOT NULL ENABLE, 
	"PARTI_MCNT" NUMBER NOT NULL ENABLE, 
	"PARTI_PRICE" NUMBER NOT NULL ENABLE, 
	"PARTI_CURR" VARCHAR2(20) NOT NULL ENABLE, 
	"PARTI_COMM" VARCHAR2(1000), 
	"PARTI_COMM_DATE" DATE, 
	 CHECK (parti_curr IN ('입금대기','입금완료')) ENABLE, 
	 CONSTRAINT "PK_P5SEMIPARTI" PRIMARY KEY ("PARTI_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  
 
  CREATE TABLE "SCOTT"."P5SEMIQNA" 
   (	"SQ_CODE" NUMBER NOT NULL ENABLE, 
	"QNA_TYPE" VARCHAR2(20) NOT NULL ENABLE, 
	"SEMI_CODE" NUMBER NOT NULL ENABLE, 
	"MEM_ID" VARCHAR2(20) NOT NULL ENABLE, 
	"SQ_DATE" DATE NOT NULL ENABLE, 
	"SQ_DETAIL" VARCHAR2(1000) NOT NULL ENABLE, 
	"QNA_ANSID" VARCHAR2(20), 
	"SQ_ANSWER" VARCHAR2(1000), 
	"QNA_ANSDATE" DATE, 
	 CHECK (qna_type IN ('세미나','밋업','세미나존')) ENABLE, 
	 CONSTRAINT "PK_P5SEMIQNA" PRIMARY KEY ("SQ_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  
 
  CREATE TABLE "SCOTT"."P5SEMIZONE" 
   (	"SZ_CODE" NUMBER NOT NULL ENABLE, 
	"SZ_TITLE" VARCHAR2(30), 
	"SZ_CAPA" NUMBER, 
	"SZ_DETAIL" VARCHAR2(2000), 
	"SZ_UNITPRICE" NUMBER, 
	"SZ_INTRO" VARCHAR2(1000), 
	"sz_notice" VARCHAR2(1000), 
	"SZ_REFUND" VARCHAR2(1000), 
	"SZ_IMG" VARCHAR2(100), 
	 CONSTRAINT "PK_P5SEMIZONE" PRIMARY KEY ("SZ_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;